//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEC_SwiftHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public System.Guid ContactId { get; set; }
        public string ContactName { get; set; }
        public string RelationShip { get; set; }
        public Nullable<int> Age { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<System.Guid> EmployeeId { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
