//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEC_SwiftHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education
    {
        public System.Guid EducationId { get; set; }
        public string SchoolName { get; set; }
        public string Department { get; set; }
        public string Degree { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> IsGraduated { get; set; }
        public string Remark { get; set; }
        public Nullable<System.Guid> EmployeeId { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
