//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEC_SwiftHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.ComputerSkills = new HashSet<ComputerSkill>();
            this.Contacts = new HashSet<Contact>();
            this.DrivingSkills = new HashSet<DrivingSkill>();
            this.Educations = new HashSet<Education>();
            this.FamilyStatues = new HashSet<FamilyStatue>();
            this.LanguageAblities = new HashSet<LanguageAblity>();
            this.WorkExperiences = new HashSet<WorkExperience>();
        }
    
        public System.Guid EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeNameEn { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string IdCardNum { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string BloodType { get; set; }
        public string MobilePhone { get; set; }
        public string Email { get; set; }
        public Nullable<System.Guid> PermanentAddressId { get; set; }
        public Nullable<System.Guid> ResidentialAddressId { get; set; }
        public string PermanentTel { get; set; }
        public string ResidentialTel { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<System.DateTime> OnBoardDate { get; set; }
        public string EmpId { get; set; }
        public Nullable<bool> IsMarried { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public Nullable<bool> HasChild { get; set; }
        public Nullable<int> NumberOfChild { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> EmployeeStatusesId { get; set; }
        public Nullable<bool> IsDisability { get; set; }
        public Nullable<bool> IsAboriginal { get; set; }
        public string PhotoPath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComputerSkill> ComputerSkills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contact> Contacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrivingSkill> DrivingSkills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Education> Educations { get; set; }
        public virtual EmployeeStatus EmployeeStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FamilyStatue> FamilyStatues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LanguageAblity> LanguageAblities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkExperience> WorkExperiences { get; set; }
        public virtual EmployeeStatus EmployeeStatus1 { get; set; }
        public virtual Address Address { get; set; }
        public virtual Address Address1 { get; set; }
    }
}
