//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEC_SwiftHR.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NewEmployeeEntities : DbContext
    {
        public NewEmployeeEntities()
            : base("name=NewEmployeeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<ComputerSkill> ComputerSkills { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<DrivingSkill> DrivingSkills { get; set; }
        public virtual DbSet<Education> Educations { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<FamilyStatue> FamilyStatues { get; set; }
        public virtual DbSet<LanguageAblity> LanguageAblities { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<WorkExperience> WorkExperiences { get; set; }
        public virtual DbSet<EmployeeStatus> EmployeeStatuses { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
    }
}
