//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEC_SwiftHR.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NewEmployeeEntities : DbContext
    {
        public NewEmployeeEntities()
            : base("name=NewEmployeeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<ComputerSkill> ComputerSkills { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<DrivingSkill> DrivingSkills { get; set; }
        public virtual DbSet<Education> Educations { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<FamilyStatue> FamilyStatues { get; set; }
        public virtual DbSet<LanguageAblity> LanguageAblities { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<PermanentAddress> PermanentAddresses { get; set; }
        public virtual DbSet<ResidentialAddress> ResidentialAddresses { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<WorkExperience> WorkExperiences { get; set; }
        public virtual DbSet<EmployeeStatus> EmployeeStatuses { get; set; }
    }
}
